[package]
name = "rustrsync"
version = "0.2.1"
authors = ["aza32nav <ivan32v7@tuta.io>"]
edition = "2018"

[dependencies]
ansi_term = "0.11.0"
toml = "0.5.6"
serde = "1.0.116"
serde_derive = "1.0.116"
structopt = "0.3.20"
